// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSDHMsjneMQ_eZKDf5h81HUEyAeXbYqbE',
    appId: '1:684574876155:web:38c7d958513492c0c02b5e',
    messagingSenderId: '684574876155',
    projectId: 'shoppingapp-430c0',
    authDomain: 'shoppingapp-430c0.firebaseapp.com',
    storageBucket: 'shoppingapp-430c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxQBLMn89AeD4S4ODdkxJJy4xIbIPdPrA',
    appId: '1:684574876155:android:eea484c7208362f1c02b5e',
    messagingSenderId: '684574876155',
    projectId: 'shoppingapp-430c0',
    storageBucket: 'shoppingapp-430c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFFDtAZ0o9sw73_0SIX50GqwaEAKhtK2Y',
    appId: '1:684574876155:ios:aa35e36bd78a2222c02b5e',
    messagingSenderId: '684574876155',
    projectId: 'shoppingapp-430c0',
    storageBucket: 'shoppingapp-430c0.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );
}
